AllCops:
  Exclude:
    - vendor/**
    - .kitchen/**/*
    - test/**/*
    - metadata.rb
    - Thorfile
    - Guardfile
    - Rakefile
Encoding:
  Enabled: false
LineLength:
  Enabled: false
RescueModifier:
  Enabled: false
